In [1]:
import zstandard as zstd
import json
import pandas as pd
import io

def load_zst_json(filepath):
    records = []
    with open(filepath, "rb") as f:
        dctx = zstd.ZstdDecompressor()
        with dctx.stream_reader(f) as reader:
            text_stream = io.TextIOWrapper(reader, encoding="utf-8")
            for line in text_stream:
                records.append(json.loads(line))
    return pd.DataFrame(records)

meta_df = load_zst_json("./reddit/subreddits/subreddits_meta_only_2025-01.zst");
wiki_df = load_zst_json("./reddit/subreddits/subreddit_wikis_2025-01.zst");

In [2]:
meta_df.head()

                                               _meta   display_name      id
0  {'earliest_comment': None, 'earliest_post': 15...   *cohold00009   7h69l
1  {'earliest_comment': None, 'earliest_post': 15...   *cohold00022   7hzhb
2  {'earliest_comment': None, 'earliest_post': 15...  *polhold00214   edn2z
3  {'earliest_comment': None, 'earliest_post': 15...  *polhold00575   7hje8
4  {'earliest_comment': None, 'earliest_post': 16...  *polhold01359  4ly4qt

In [3]:
print(meta_df.shape)
print(meta_df.columns.tolist())
print(meta_df["_meta"][2131])

(1638637, 3)
['_meta', 'display_name', 'id']
{'earliest_comment': None, 'earliest_post': 1665033847, 'num_comments': None, 'num_comments_updated_at': None, 'num_posts': 2, 'num_posts_updated_at': 1739731892}

In [4]:
wiki_df.head()

,content,path,retrieved_on,revision_author,revision_author_id,revision_date,revision_reason
0,Here are possible solutions you can try that I...,/r/001Guy001/wiki/index,1737155927,001Guy001,1299b0,2024-11-17T17:45:02+00:00,NaN
1,:::\n\n“Welcome to the most ancient conspiracy...,/r/00AG9603/wiki/index,1737235480,minimalista,7km5s,2024-09-12T23:35:46+00:00,NaN
2,\nIndividuals are encouraged and controlled in...,/r/00AG9603/wiki/index/open_login_-_reality_gl...,1737306258,minimalista,7km5s,2020-01-16T13:00:08+00:00,NaN
3,Other Pages: \r\n[People](https://reddit.com/...,/r/00weareready00/wiki/index,1737155927,MegaMCAlly,ayu74,2016-06-22T19:36:59+00:00,NaN
4,[Back to Main Page](https://www.reddit.com/r/0...,/r/00weareready00/wiki/people,1737155925,MegaMCAlly,ayu74,2016-06-22T23:53:01+00:00,NaN

In [5]:
print(wiki_df.shape)
print(wiki_df.columns.tolist())
print(wiki_df["content"][4])

(322964, 7)
['content', 'path', 'retrieved_on', 'revision_author', 'revision_author_id', 'revision_date', 'revision_reason']
[Back to Main Page](https://www.reddit.com/r/00weareready00/wiki/index)

A list of people known to be involved in the ARG.

Known to be Official:

        Name:
            Nigel
        Stats:
            Protagonist, Main Character
        Twitter:
            @00weareready00

        Name:
            Watch
        Stats:
            Antagonist(s?)
        Twitter:
            @wa_tch_

        Name:
            Matt
        Stats:
            Protagonist (Exact role undetermined)
        Twitter:
            @Dont1worry

Unsure if Official or Not (as of now):

    N/A

Skitzes (Gamejackers):

        Name:
            ???
        Stats:
            Skitz
        Twitter:
            @15xanswersx15

In [6]:
def get_subreddit_name(path):
    subreddit_name = path.split("/")[2]
    return subreddit_name

wiki_df["SUBREDDIT_NAME"] = wiki_df["path"].apply(get_subreddit_name)
selected_wiki_df = wiki_df[["SUBREDDIT_NAME", "content"]]

In [7]:
selected_wiki_df.to_csv("./data/wiki_df.csv", index=False)

In [8]:
selected_wiki_df.isin(["soccer"]).any()

SUBREDDIT_NAME     True
content           False
dtype: bool

In [ ]:
import os
size = os.path.getsize("./data/wiki_df.csv")
print(f"File size: {size} bytes")